name: ${PROJECT}

networks:
  proxy:
    external: true
  default:
    external: true
    name: proxy

services:
  # usememos - Lightweight note-taking app
  memos:
    container_name: hl-memos
    image: neosmemo/memos:stable
    volumes:
      - ${VOLUMES_PATH}/memos:/var/opt/memos:z
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.3"
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.services.hl-memos.loadbalancer.server.port=5230"
      - "traefik.http.routers.hl-memos.rule=Host(`notes.${DOMAIN}`)"
      - "traefik.http.routers.hl-memos.middlewares=robots-deny@file"
      - "traefik.http.routers.hl-memos.entrypoints=websecure"
      - "traefik.http.routers.hl-memos.tls=true"
      - "traefik.http.routers.hl-memos.tls.certresolver=myresolver"
