// before.deploy.ts — Syncthing-specific pre-deploy hook.
//
// Reads servers/<server>/syncthing.yml, then:
//   1. Ensures host paths for data_dir and all mounts exist (ssh mkdir).
//   2. Generates stacks/syncthing/docker-compose.override.yml with the
//      volume bind mounts. This file is committed to tempDir (via rsync)
//      so docker compose picks it up automatically.
//
// No env-file writes — SYNCTHING_API_KEY lives in the server's .env, not here.
//
// Idempotent: re-running produces the same override file. Skips silently if
// servers/<server>/syncthing.yml is missing.

import { parse as parseYaml } from "yaml"

interface Mount {
  host: string
  container: string
}

interface Folder {
  id: string
  path: string
  type?: string
  devices: string[]
}

interface Device {
  id: string
  name?: string
}

interface SyncthingConfig {
  data_dir: string
  mounts?: Mount[]
  folders?: Folder[]
  devices?: Device[]
}

const SSH = Deno.env.get("SSH_ADDRESS") ?? ""
const SERVER = Deno.env.get("DEPLOY_AS") ?? Deno.env.get("SERVER_NAME") ?? ""
const USER = Deno.env.get("HOMELAB_USER") ?? "spy4x"

if (!SERVER) {
  console.error("before.deploy.ts: DEPLOY_AS / SERVER_NAME not set")
  Deno.exit(1)
}

// Config path: prefer `configs/syncthing.yml` (matches the deploy tempDir
// layout where `configs/` is copied to the tempDir root). Fall back to
// `servers/<server>/configs/syncthing.yml` for local development from the
// repo root.
const configPaths = [
  "configs/syncthing.yml",
  `servers/${SERVER}/configs/syncthing.yml`,
]

let configPath: string | null = null
for (const p of configPaths) {
  try {
    await Deno.stat(p)
    configPath = p
    break
  } catch {
    // try next
  }
}

if (!configPath) {
  console.log(`No syncthing.yml found in ${configPaths.join(", ")} — skipping`)
  Deno.exit(0)
}

const text = await Deno.readTextFile(configPath)
const config = parseYaml(text) as SyncthingConfig
console.log(`Loaded ${configPath}`)

if (!config.data_dir) {
  console.error(`${configPath}: data_dir is required`)
  Deno.exit(1)
}

function expandHome(p: string): string {
  if (p.startsWith("~/")) return `/home/${USER}${p.slice(1)}`
  return p
}

// Build the list of host paths to ensure exist
const hostPaths: string[] = []
hostPaths.push(expandHome(config.data_dir))
for (const m of config.mounts ?? []) {
  hostPaths.push(expandHome(m.host))
}

// Ensure each host path exists on the remote server (only when SSH is set).
const runOnRemote = async (cmd: string): Promise<string> => {
  if (SSH) {
    const proc = new Deno.Command("ssh", {
      args: [SSH, cmd],
      stdout: "piped",
      stderr: "piped",
    })
    const out = await proc.output()
    if (out.code !== 0) {
      throw new Error(new TextDecoder().decode(out.stderr).trim())
    }
    return new TextDecoder().decode(out.stdout)
  }
  // Local mode (e.g., when running deploy from the same host as syncthing).
  const proc = new Deno.Command("bash", {
    args: ["-c", cmd],
    stdout: "piped",
    stderr: "piped",
  })
  const out = await proc.output()
  if (out.code !== 0) {
    throw new Error(new TextDecoder().decode(out.stderr).trim())
  }
  return new TextDecoder().decode(out.stdout)
}

for (const hostPath of hostPaths) {
  const cmd = `mkdir -p "${hostPath}" && chown ${USER}:${USER} "${hostPath}" 2>/dev/null || true`
  try {
    await runOnRemote(cmd)
    console.log(`✓ ${hostPath}`)
  } catch (err) {
    console.error(`Failed to prepare ${hostPath}:`)
    console.error(err instanceof Error ? err.message : String(err))
    Deno.exit(1)
  }
}

// Generate docker-compose.override.yml in tempDir/stacks/syncthing/
const overrideLines = [
  "# AUTO-GENERATED by stacks/syncthing/before.deploy.ts — do not edit by hand.",
  `# Source of truth: ${configPath}`,
  "services:",
  "  syncthing:",
  "    volumes:",
  // data_dir is bind-mounted to /var/syncthing (syncthing expects the config dir there)
  `      - "${expandHome(config.data_dir)}:/var/syncthing:z"`,
  // localtime for consistent timestamps in logs
  `      - "/etc/localtime:/etc/localtime:ro,z"`,
]
for (const m of config.mounts ?? []) {
  overrideLines.push(`      - "${expandHome(m.host)}:${m.container}:z"`)
}

const overridePath = "stacks/syncthing/docker-compose.override.yml"
await Deno.writeTextFile(overridePath, overrideLines.join("\n") + "\n")
console.log(`✓ ${overridePath}`)
