name: ${PROJECT}

networks:
  proxy:
    external: true
  default:
    external: true
    name: proxy

services:
  # Syncthing is a continuous file synchronization program.
  # It synchronizes files between two or more computers in real time, safely protected from prying eyes.
  syncthing:
    container_name: hl-syncthing
    image: syncthing/syncthing:2.1.1
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      - ${VOLUMES_PATH}/syncthing:/var/syncthing:z
      - /etc/localtime:/etc/localtime:ro,z
      - ${PATH_SYNC}:/sync:z
    ports:
      - 22000:22000/tcp # Sync protocol (BEP)
      - 22000:22000/udp # QUIC connections
      - 21027:21027/udp # Discovery broadcasts
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: ${SYNCTHING_CPU_LIMIT:-1}
          memory: ${SYNCTHING_MEM_LIMIT:-1024M}
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.services.hl-syncthing.loadbalancer.server.port=8384"
      - "traefik.http.routers.hl-syncthing.rule=Host(`${SYNCTHING_SUBDOMAIN}.${DOMAIN}`)"
      - "traefik.http.routers.hl-syncthing.middlewares=robots-deny@file"
      - "traefik.http.routers.hl-syncthing.entrypoints=websecure"
      - "traefik.http.routers.hl-syncthing.tls=true"
      - "traefik.http.routers.hl-syncthing.tls.certresolver=myresolver"
