// Stack metadata for `traefik`.
//
// First 6 stacks tracked by the v1 catalog (docs/v1-cli.md §11, Phase 4).
// Traefik is the reverse proxy that fronts the catalog — every other
// stack's `<SERVICE>_DOMAIN` is a Traefik label.
//
// TRAEFIK_DOMAIN holds the full host (not a subdomain fragment) per the
// single `<SERVICE>_DOMAIN` convention — compose reads
// `Host(\`${TRAEFIK_DOMAIN}\`)` directly, no `${DOMAIN}` concatenation.
//
// CONTACT_EMAIL is a server-level key (`server create` writes it, every
// stack that needs ACME reads it) — not declared here.
//
// TRAEFIK_BASIC_AUTH_USER / TRAEFIK_BASIC_AUTH_PASSWORD drive the
// dashboard's `.htpasswd`, generated by `before.deploy.ts`. A generated
// password means `stack add traefik -n` produces a working dashboard
// with no manual edits.

import type { StackMeta } from "@rostok/cli"
import { generatePassword } from "@rostok/cli"

export default {
  name: "traefik",
  description: "Reverse proxy with auto-TLS via Let's Encrypt",
  category: "proxy",
  variables: [
    {
      key: "TRAEFIK_IMAGE_TAG",
      default: "3.7.6",
      required: false,
    },
    {
      key: "TRAEFIK_DOMAIN",
      question: "Public domain for the Traefik dashboard?",
      // v1 design: ${DOMAIN} resolves to the server's apex domain
      // (set during server-create). Wizard pre-fills this as editable.
      default: "traefik.${DOMAIN}",
      required: true,
    },
    {
      key: "TRAEFIK_BASIC_AUTH_USER",
      question: "Traefik dashboard basic-auth username?",
      default: "admin",
      required: true,
    },
    {
      key: "TRAEFIK_BASIC_AUTH_PASSWORD",
      question: "Traefik dashboard basic-auth password?",
      default: () => generatePassword(24),
      required: true,
      secret: true,
    },
    {
      key: "TRAEFIK_CPU_LIMIT",
      question: "CPU limit for the Traefik container?",
      default: "1",
      required: true,
    },
    {
      key: "TRAEFIK_MEM_LIMIT",
      question: "Memory limit for the Traefik container?",
      default: "512M",
      required: true,
    },
  ],
} satisfies StackMeta
