name: ${PROJECT}

networks:
  proxy:
    external: true
  default:
    external: true
    name: proxy

services:
  # traggo - Self-hosted time tracking
  # https://github.com/traggo/traggo
  traggo:
    container_name: hl-traggo
    image: traggo/server:latest
    environment:
      - TZ=${TIMEZONE:-UTC}
      - TRAGGO_PORT=3030
    volumes:
      - ${VOLUMES_PATH}/traggo/data:/opt/traggo/data:z
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: ${TIMETRACKER_MEM_LIMIT:-128M}
          cpus: ${TIMETRACKER_CPU_LIMIT:-0.2}
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.services.hl-traggo.loadbalancer.server.port=3030"
      - "traefik.http.routers.hl-traggo.rule=Host(`time.${DOMAIN}`)"
      - "traefik.http.routers.hl-traggo.entrypoints=websecure"
      - "traefik.http.routers.hl-traggo.tls=true"
      - "traefik.http.routers.hl-traggo.middlewares=authelia@file,robots-deny@file"
      - "traefik.http.routers.hl-traggo.tls.certresolver=myresolver"
