networks:
  proxy:
    external: true
  default:
    external: true
    name: proxy

services:
  # Audiobookshelf is a self-hosted audio & epub/pdf book server.
  audiobookshelf:
    container_name: hl-audiobookshelf
    image: ghcr.io/advplyr/audiobookshelf:latest
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TIMEZONE}
    volumes:
      - ${VOLUMES_PATH}/audiobookshelf/config:/config:z
      - ${VOLUMES_PATH}/audiobookshelf-metadata:/metadata:z
      - ${PATH_BOOKS}:/audiobooks:z
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1024M
          cpus: "1"
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.services.hl-audiobookshelf.loadbalancer.server.port=80"
      - "traefik.http.routers.hl-audiobookshelf.rule=Host(`books.${DOMAIN}`)"
      - "traefik.http.routers.hl-audiobookshelf.middlewares=robots-deny@file"
      - "traefik.http.routers.hl-audiobookshelf.entrypoints=websecure"
      - "traefik.http.routers.hl-audiobookshelf.tls=true"
      - "traefik.http.routers.hl-audiobookshelf.tls.certresolver=myresolver"
