apiVersion: 1

datasources:
  - name: VictoriaMetrics
    type: prometheus
    access: proxy
    url: http://hl-victoria-metrics:8428
    isDefault: true
    editable: false

  - name: VictoriaLogs
    type: loki
    access: proxy
    url: http://hl-victoria-logs:9428
    editable: false
