/**
 * Install git hooks for automatic env encryption/decryption.
 *
 * Resolves shared .git/hooks/ directory (works with worktrees where
 * .git is a file, not a directory). Writes hook scripts directly
 * instead of depending on deno-task-hooks (which only supports a
 * limited subset of hook types).
 */

const COMMON_DIR = Deno.env.get("GIT_DIR") || resolveGitCommonDir()
const HOOKS_DIR = join(COMMON_DIR, "hooks")

// git exports GIT_DIR/GIT_COMMON_DIR/GIT_WORK_TREE/GIT_INDEX_FILE to a
// hook's own environment so a git command the hook runs targets the
// commit/checkout/merge in progress. `deno task check`/`env:encrypt`/
// `env:decrypt` — this hook's own commands — end up spawning `git`
// themselves too (cli/age.ts's resolveKeyFile, run by anything that
// touches .env.age), and would inherit those same variables: a test
// suite that also spawns `git` in a throwaway repo (cli/age.test.ts's
// own coverage of this exact class of bug) would then operate on the
// REAL repo/index/branch being committed instead of its own throwaway
// one — a real security review of this repo caught exactly that. Unset
// before running anything, in every hook that can reach a git spawn.
const UNSET_GIT_ENV = "unset GIT_DIR GIT_COMMON_DIR GIT_WORK_TREE GIT_INDEX_FILE"

const hooks: Record<string, string> = {
  "pre-commit": `#!/bin/sh
# Auto-generated by rostok hooks/install.ts
set -eu
${UNSET_GIT_ENV}
deno task check && deno task env:encrypt
`,
  "post-checkout": `#!/bin/sh
# Auto-generated by rostok hooks/install.ts
set -eu
${UNSET_GIT_ENV}
deno task env:decrypt
`,
  "post-merge": `#!/bin/sh
# Auto-generated by rostok hooks/install.ts
set -eu
${UNSET_GIT_ENV}
deno task env:decrypt
`,
}

function resolveGitCommonDir(): string {
  const cmd = new Deno.Command("git", {
    args: ["rev-parse", "--git-common-dir"],
    stdout: "piped",
    stderr: "piped",
  })
  const { code, stdout } = cmd.outputSync()
  if (code === 0) {
    return new TextDecoder().decode(stdout).trim()
  }
  // Fallback
  return join(Deno.cwd(), ".git")
}

function join(...parts: string[]): string {
  return parts.join("/")
}

async function main() {
  console.log(`Installing hooks in: ${HOOKS_DIR}`)

  try {
    await Deno.mkdir(HOOKS_DIR, { recursive: true })
  } catch { /* exists */ }

  let installed = 0
  for (const [name, script] of Object.entries(hooks)) {
    const path = join(HOOKS_DIR, name)
    try {
      // Check if already installed with same content
      const existing = await Deno.readTextFile(path)
      if (existing.trim() === script.trim()) {
        console.log(`  ${name}: already installed`)
        continue
      }
    } catch { /* not exists — install */ }

    await Deno.writeTextFile(path, script)
    if (Deno.build.os !== "windows") {
      await Deno.chmod(path, 0o755)
    }
    console.log(`  ${name}: installed`)
    installed++
  }

  console.log(`\nDone. ${installed} hook(s) installed.`)
}

if (import.meta.main) await main()
