/**
 * Install git hooks for automatic env encryption/decryption.
 *
 * Resolves shared .git/hooks/ directory (works with worktrees where
 * .git is a file, not a directory). Writes hook scripts directly
 * instead of depending on deno-task-hooks (which only supports a
 * limited subset of hook types).
 */

const COMMON_DIR = Deno.env.get("GIT_DIR") || resolveGitCommonDir()
const HOOKS_DIR = join(COMMON_DIR, "hooks")

const hooks: Record<string, string> = {
  "pre-commit": `#!/bin/sh
# Auto-generated by rostok hooks/install.ts
set -eu
deno task check && deno task env:encrypt
`,
  "post-checkout": `#!/bin/sh
# Auto-generated by rostok hooks/install.ts
set -eu
deno task env:decrypt
`,
  "post-merge": `#!/bin/sh
# Auto-generated by rostok hooks/install.ts
set -eu
deno task env:decrypt
`,
}

function resolveGitCommonDir(): string {
  const cmd = new Deno.Command("git", {
    args: ["rev-parse", "--git-common-dir"],
    stdout: "piped",
    stderr: "piped",
  })
  const { code, stdout } = cmd.outputSync()
  if (code === 0) {
    return new TextDecoder().decode(stdout).trim()
  }
  // Fallback
  return join(Deno.cwd(), ".git")
}

function join(...parts: string[]): string {
  return parts.join("/")
}

async function main() {
  console.log(`Installing hooks in: ${HOOKS_DIR}`)

  try {
    await Deno.mkdir(HOOKS_DIR, { recursive: true })
  } catch { /* exists */ }

  let installed = 0
  for (const [name, script] of Object.entries(hooks)) {
    const path = join(HOOKS_DIR, name)
    try {
      // Check if already installed with same content
      const existing = await Deno.readTextFile(path)
      if (existing.trim() === script.trim()) {
        console.log(`  ${name}: already installed`)
        continue
      }
    } catch { /* not exists — install */ }

    await Deno.writeTextFile(path, script)
    if (Deno.build.os !== "windows") {
      await Deno.chmod(path, 0o755)
    }
    console.log(`  ${name}: installed`)
    installed++
  }

  console.log(`\nDone. ${installed} hook(s) installed.`)
}

if (import.meta.main) await main()
